### ISSUE TITLE
Bash scripts for updating and running

### ISSUE THREAD

**Issue by syko** [toggl/gamebot#2]
We should come up with a script that is called every time the machine boots that updates the bot and runs it. We could also hard code everything in the bash script of sets up the whole machine but it's more flexible for us if we can do some things in our own scripts.

toggl-hubot has this:
https://github.com/toggl/toggl-hubot/tree/master/bin

Every time the machine is set up or rebooted this is run:
`exec bin/update-and-run --name "toggl-hubot" --adapter "slack" 2>&1 | logger -t hubot-slack`

The full setup script for hubot is here (requires staging vpn): https://gogs.toggl.space/toggl/boft-roles/src/master/hubot.sh

To create that :point_up: we need the TOKEN and possibly other env vars.

**Comment by dooart** [comment]
i can only build the bot with node v7.5.0 because of the package `lwip` (that we're using in crisis), so maybe we should use that version in production

ps: remember to set the env var `PRODUCTION=true`

**Comment by syko** [comment]
oh ok. I guess we should target 7.5.0 then

**Comment by syko** [comment]
Are there any environment variables we want to pass in to the bot?
Marvin has these for example: `HUBOT_DEFAULT_CHANNEL`, `HUBOT_BOT_NAME`.

And when do we have to pass in `PRODUCTION=true`. When building?

**Comment by dooart** [comment]
`TOKEN=xxxxx PRODUCTION=true`, only when running

(i put the info [here](https://github.com/toggl/gamebot/blob/master/README.md) btw)

**Comment by syko** [comment]
yeah was just wondering if there could be anything more
